"""S3 presigned URL generation for media uploads and downloads.

Uploads use presigned PUT URLs (the frontend contract). The signature
pins the ``Content-Type`` to an allowlisted MIME type and, when the client
declares it, the exact ``Content-Length`` (capped at 10 MB). Object keys are
generated server side: a random UUID, a sanitised stem and an extension
derived from the MIME type, never from the client filename.
"""

import re
from functools import lru_cache
from pathlib import PurePosixPath
from typing import Any
from uuid import uuid4

from src.config import get_settings
from src.schemas.media import (
    MediaPrefix,
    PresignDownloadResponse,
    PresignUploadRequest,
    PresignUploadResponse,
)
from src.services.errors import InvalidInputError
from src.utils.aws_clients import get_client
from src.utils.slugify import slugify

CV_KEY = f"{MediaPrefix.CV.value}cv.pdf"

# MIME type -> file extension. SVG is excluded on purpose (it can carry script).
_IMAGE_TYPES = {
    "image/png": "png",
    "image/jpeg": "jpg",
    "image/webp": "webp",
    "image/gif": "gif",
}
_CV_TYPES = {"application/pdf": "pdf"}
_ALLOWED_TYPES: dict[MediaPrefix, dict[str, str]] = {
    MediaPrefix.PROJECT_IMAGES: _IMAGE_TYPES,
    MediaPrefix.LEARNING_IMAGES: _IMAGE_TYPES,
    MediaPrefix.CV: _CV_TYPES,
}
_MAX_STEM_LENGTH = 64

# Keys the public download endpoint may sign: the CV singleton, or an image
# key as generated by ``_object_key`` (32-hex UUID, slug stem, image ext).
# ``jpeg`` is accepted for images uploaded before extensions were normalised.
_DOWNLOADABLE_KEY = re.compile(
    rf"^(?:{re.escape(CV_KEY)}"
    r"|images/(?:projects|learning)/[0-9a-f]{32}-[a-z0-9-]{1,200}"
    r"\.(?:png|jpg|jpeg|webp|gif))$"
)


class MediaService:
    """Issue short-lived presigned URLs for the media bucket."""

    def __init__(self) -> None:
        settings = get_settings()
        # SigV4 is required to sign the ``content-length`` header.
        self._client = get_client("s3", settings.aws_region, "s3v4")
        self._bucket = settings.media_bucket_name
        self._expiration = settings.presign_expiration_seconds

    def create_upload_url(self, payload: PresignUploadRequest) -> PresignUploadResponse:
        """Create a presigned PUT URL under an allowed prefix.

        Parameters
        ----------
        payload : PresignUploadRequest
            Destination prefix, original filename, MIME type and optional
            exact size.

        Returns
        -------
        PresignUploadResponse
            Presigned URL, final object key and expiry.

        Raises
        ------
        InvalidInputError
            When the MIME type is not allowed for the prefix.
        """
        extension = _extension_for(payload.prefix, payload.content_type)
        key = _object_key(payload.prefix, payload.filename, extension)
        params: dict[str, Any] = {
            "Bucket": self._bucket,
            "Key": key,
            "ContentType": payload.content_type,
        }
        if payload.content_length is not None:
            params["ContentLength"] = payload.content_length
        url = self._client.generate_presigned_url(
            "put_object", Params=params, ExpiresIn=self._expiration
        )
        return PresignUploadResponse(url=url, key=key, expires_in=self._expiration)

    def create_download_url(self, key: str) -> PresignDownloadResponse:
        """Create a presigned GET URL for a public media object.

        Parameters
        ----------
        key : str
            S3 object key: the CV (``cv/cv.pdf``) or a generated image key.

        Returns
        -------
        PresignDownloadResponse
            Presigned URL, object key and expiry.

        Raises
        ------
        InvalidInputError
            When the key does not match a downloadable key format.
        """
        if not _DOWNLOADABLE_KEY.fullmatch(key):
            raise InvalidInputError("Key is not a downloadable media object.")
        url = self._client.generate_presigned_url(
            "get_object",
            Params={"Bucket": self._bucket, "Key": key},
            ExpiresIn=self._expiration,
        )
        return PresignDownloadResponse(url=url, key=key, expires_in=self._expiration)


def _extension_for(prefix: MediaPrefix, content_type: str) -> str:
    """Return the file extension for an allowlisted MIME type.

    Parameters
    ----------
    prefix : MediaPrefix
        Destination prefix.
    content_type : str
        MIME type declared by the client.

    Returns
    -------
    str
        Lowercase extension without the dot.

    Raises
    ------
    InvalidInputError
        When the MIME type is not allowed under the prefix.
    """
    allowed = _ALLOWED_TYPES[prefix]
    if content_type not in allowed:
        accepted = ", ".join(sorted(allowed))
        raise InvalidInputError(f"Content type must be one of: {accepted}.")
    return allowed[content_type]


def _object_key(prefix: MediaPrefix, filename: str, extension: str) -> str:
    """Build the S3 object key for an upload.

    The CV is a singleton document stored at a fixed key (``cv/cv.pdf``) so
    the public download button can always find it and re-uploads replace it.
    Images get a unique key to avoid collisions.

    Parameters
    ----------
    prefix : MediaPrefix
        Destination prefix.
    filename : str
        Original filename (only its sanitised stem is used, for images).
    extension : str
        Extension derived from the allowlisted MIME type.

    Returns
    -------
    str
        The S3 object key.
    """
    if prefix is MediaPrefix.CV:
        return CV_KEY
    return f"{prefix.value}{uuid4().hex}-{_safe_stem(filename)}.{extension}"


def _safe_stem(filename: str) -> str:
    """Reduce a filename to a short ``[a-z0-9-]`` slug (``file`` if empty)."""
    stem = slugify(PurePosixPath(filename).stem)[:_MAX_STEM_LENGTH].strip("-")
    return stem or "file"


@lru_cache
def get_media_service() -> MediaService:
    """Return the cached :class:`MediaService`.

    Built once per execution environment so boto3 objects are reused
    across requests; tests clear it with ``cache_clear()``.

    Returns
    -------
    MediaService
        Shared service instance.
    """
    return MediaService()
