# S3 buckets.
#
#   frontend : built SPA assets, fully private. CloudFront reads it through
#              an Origin Access Control; the bucket policy that allows this
#              lives in the cdn module (it needs the distribution ARN).
#   media    : project/learning images and CV exports under the prefixes
#              images/projects/, images/learning/ and cv/. Fully private,
#              accessed only via presigned URLs generated by the backend.
#
# Both buckets: SSE-S3 encryption, versioning, all public access blocked,
# TLS-only access (aws:SecureTransport deny). The frontend TLS deny is merged
# into the OAC bucket policy in the cdn module (a bucket has one policy).

locals {
  buckets = {
    frontend = "${var.project_name}-frontend"
    media    = "${var.project_name}-media"
  }
}

resource "aws_s3_bucket" "this" {
  for_each = local.buckets

  bucket = each.value
}

resource "aws_s3_bucket_versioning" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  versioning_configuration {
    status = "Enabled"
  }
}

# SSE-S3 (AES256) on purpose: public site assets and portfolio images do not
# justify a customer-managed KMS key (cost + per-request KMS charges).
#trivy:ignore:AVD-AWS-0132
resource "aws_s3_bucket_server_side_encryption_configuration" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_public_access_block" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

# Browsers upload/download media through presigned URLs, so the media bucket
# needs CORS for the site origin (plus localhost for development).
resource "aws_s3_bucket_cors_configuration" "media" {
  bucket = aws_s3_bucket.this["media"].id

  cors_rule {
    allowed_methods = ["GET", "PUT", "HEAD"]
    allowed_origins = [
      "https://${var.domain_name}",
      "https://www.${var.domain_name}",
      "http://localhost:5173",
    ]
    allowed_headers = ["*"]
    max_age_seconds = 3600
  }
}

# Keep storage costs flat: drop non-current object versions after 30 days
# (on the frontend bucket every deploy overwrites index.html & co.).
resource "aws_s3_bucket_lifecycle_configuration" "this" {
  for_each = aws_s3_bucket.this

  bucket = each.value.id

  rule {
    id     = "expire-noncurrent-versions"
    status = "Enabled"

    filter {}

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}

# Media bucket policy: refuse any request not made over TLS.
data "aws_iam_policy_document" "media" {
  statement {
    sid     = "DenyInsecureTransport"
    effect  = "Deny"
    actions = ["s3:*"]
    resources = [
      aws_s3_bucket.this["media"].arn,
      "${aws_s3_bucket.this["media"].arn}/*",
    ]

    principals {
      type        = "*"
      identifiers = ["*"]
    }

    condition {
      test     = "Bool"
      variable = "aws:SecureTransport"
      values   = ["false"]
    }
  }
}

resource "aws_s3_bucket_policy" "media" {
  bucket = aws_s3_bucket.this["media"].id
  policy = data.aws_iam_policy_document.media.json

  depends_on = [aws_s3_bucket_public_access_block.this]
}

# The media lifecycle rule used to be a standalone resource; keep its state.
moved {
  from = aws_s3_bucket_lifecycle_configuration.media
  to   = aws_s3_bucket_lifecycle_configuration.this["media"]
}
